# This file was auto-generated by Polybuild

ifndef OS
	OS := $(shell uname)
endif

obj_ext := .o
ifeq ($(OS),Windows_NT)
	obj_ext := .obj
	out_ext := .exe
endif

compiler := zcc
compilation_flags := +ti83p -create-app -startup=10
libraries := -lm

default: symbol$(out_ext)
.PHONY: default

obj/console_0$(obj_ext): ./console.c ./console.h
	@printf '\033[1m[POLYBUILD]\033[0m Compiling $@ from $<...\n'
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf '\033[1m[POLYBUILD]\033[0m Finished compiling $@ from $<!\n'

obj/main_0$(obj_ext): ./main.c ./console.h
	@printf '\033[1m[POLYBUILD]\033[0m Compiling $@ from $<...\n'
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf '\033[1m[POLYBUILD]\033[0m Finished compiling $@ from $<!\n'

obj/parser_0$(obj_ext): ./parser.c ./parser.h
	@printf '\033[1m[POLYBUILD]\033[0m Compiling $@ from $<...\n'
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf '\033[1m[POLYBUILD]\033[0m Finished compiling $@ from $<!\n'

symbol$(out_ext): obj/console_0$(obj_ext) obj/main_0$(obj_ext) obj/parser_0$(obj_ext)
	@printf '\033[1m[POLYBUILD]\033[0m Building $@...\n'
	@$(compiler) $^ $(static_libraries) $(compilation_flags) $(libraries) -o $@
	@printf '\033[1m[POLYBUILD]\033[0m Finished building $@!\n'

clean:
	@printf '\033[1m[POLYBUILD]\033[0m Executing clean prelude: rm -f symbol.8xp\n'
	@rm -f symbol.8xp
	@printf '\033[1m[POLYBUILD]\033[0m Deleting symbol$(out_ext) and obj...\n'
	@rm -rf symbol$(out_ext) obj
	@printf '\033[1m[POLYBUILD]\033[0m Finished deleting symbol$(out_ext) and obj!\n'
.PHONY: clean
